extends:
- semistandard
- plugin:lodash-fp/recommended
plugins:
- lodash-fp
rules:
  strict:
  - error
  - safe
  valid-jsdoc: error
  require-jsdoc:
  - error
  - require:
      FunctionDeclaration: true
      MethodDefinition: true
      ClassDeclaration: true
